// packages/atom/solid/src/RegistryContext.ts
/**
 * The `RegistryContext` module provides the Solid context used by Effect Atom
 * hooks to share an `AtomRegistry` across an owner tree. The registry owns atom
 * state, scheduling, and idle cleanup, so Solid components that read or write
 * atoms coordinate through the same runtime instead of creating isolated
 * registries.
 *
 * **Common tasks**
 *
 * - Use {@link RegistryProvider} to scope atom state to a Solid subtree
 * - Seed atoms for tests, examples, or server-provided data with `initialValues`
 * - Override scheduling or idle timing for custom rendering environments
 * - Read {@link RegistryContext} when integrating lower-level atom APIs
 *
 * **Gotchas**
 *
 * - The provider creates a registry for the current Solid owner and disposes it
 *   with `onCleanup`
 * - `initialValues` are applied when the provider creates the registry, not as
 *   reactive updates after creation
 * - Overriding `scheduleTask` changes when atom work is flushed, so it should
 *   return a cancellation function that is safe to call during Solid cleanup
 *
 * @since 1.0.0
 */
import type * as Atom from "effect/unstable/reactivity/Atom"
import * as AtomRegistry from "effect/unstable/reactivity/AtomRegistry"
import type { JSX } from "solid-js"
import { createComponent, createContext, onCleanup } from "solid-js"

/**
 * @category context
 * @since 1.0.0
 */
export const RegistryContext = createContext<AtomRegistry.AtomRegistry>(AtomRegistry.make())

/**
 * @category context
 * @since 1.0.0
 */
export const RegistryProvider = (options: {
  readonly children?: JSX.Element | undefined
  readonly initialValues?: Iterable<readonly [Atom.Atom<any>, any]> | undefined
  readonly scheduleTask?: ((f: () => void) => () => void) | undefined
  readonly timeoutResolution?: number | undefined
  readonly defaultIdleTTL?: number | undefined
}) => {
  const registry = AtomRegistry.make({
    scheduleTask: options.scheduleTask,
    initialValues: options.initialValues,
    timeoutResolution: options.timeoutResolution,
    defaultIdleTTL: options.defaultIdleTTL ?? 400
  })
  onCleanup(() => registry.dispose())
  return createComponent(RegistryContext.Provider, {
    value: registry,
    get children() {
      return options.children
    }
  })
}

// packages/atom/react/src/RegistryContext.ts
/**
 * The `RegistryContext` module provides the React context used by Effect Atom
 * hooks to share an `AtomRegistry` across a component tree. The registry owns
 * atom state, scheduling, and idle cleanup, so components that read or write
 * atoms can coordinate through the same runtime instead of each creating an
 * isolated registry.
 *
 * **Common tasks**
 *
 * - Use {@link RegistryProvider} to scope atom state to a React subtree
 * - Seed atoms for tests, stories, or server-provided data with `initialValues`
 * - Override scheduling or idle timing for custom rendering environments
 * - Read {@link RegistryContext} when integrating lower-level atom APIs
 *
 * **Gotchas**
 *
 * - This is a client module because it depends on React runtime hooks and the
 *   scheduler package
 * - A provider keeps the registry stable across renders and disposes it shortly
 *   after unmount, allowing React remounts to reuse the same registry
 * - Overriding `scheduleTask` changes when atom work is flushed, so it should
 *   return a cancellation function compatible with React unmounts
 *
 * @since 1.0.0
 */
"use client"

import type * as Atom from "effect/unstable/reactivity/Atom"
import * as AtomRegistry from "effect/unstable/reactivity/AtomRegistry"
import * as React from "react"
import * as Scheduler from "scheduler"

/**
 * @category context
 * @since 1.0.0
 */
export function scheduleTask(f: () => void): () => void {
  const node = Scheduler.unstable_scheduleCallback(Scheduler.unstable_LowPriority, f)
  return () => Scheduler.unstable_cancelCallback(node)
}

/**
 * @category context
 * @since 1.0.0
 */
export const RegistryContext = React.createContext<AtomRegistry.AtomRegistry>(AtomRegistry.make({
  scheduleTask,
  defaultIdleTTL: 400
}))

/**
 * @category context
 * @since 1.0.0
 */
export const RegistryProvider = (options: {
  readonly children?: React.ReactNode | undefined
  readonly initialValues?: Iterable<readonly [Atom.Atom<any>, any]> | undefined
  readonly scheduleTask?: ((f: () => void) => () => void) | undefined
  readonly timeoutResolution?: number | undefined
  readonly defaultIdleTTL?: number | undefined
}) => {
  const ref = React.useRef<{
    readonly registry: AtomRegistry.AtomRegistry
    timeout?: number | undefined
  }>(null)
  if (ref.current === null) {
    ref.current = {
      registry: AtomRegistry.make({
        scheduleTask: options.scheduleTask ?? scheduleTask,
        initialValues: options.initialValues,
        timeoutResolution: options.timeoutResolution,
        defaultIdleTTL: options.defaultIdleTTL
      })
    }
  }
  React.useEffect(() => {
    if (ref.current?.timeout !== undefined) {
      clearTimeout(ref.current.timeout)
    }
    return () => {
      ref.current!.timeout = setTimeout(() => {
        ref.current?.registry.dispose()
        ref.current = null
      }, 500) as any
    }
  }, [ref])
  return React.createElement(RegistryContext.Provider, { value: ref.current.registry }, options?.children)
}
